# Do not change version. This is the version of aws buildspec, not the version of your buildspec file.
version: 0.2

env:
  variables:
    IMAGE_NAME: 'wallaby'
    IMAGE_NETWORK: 'wallabynet'
    CUSTOM_WALLABY_TAG: 'f8-wallaby-latest'
    PROJECT: 'filecoin'
    ENVIRONMENT: 'mainnet'
    SUB_ENV: 'glif'
    SHORT_REGION: 'apn1'
    AWS_ACCOUNT_ID: '499623857295'
    DOCKERUHUB_ORGANIZATION: 'glif'
  secrets-manager:
    DOCKERHUB_USERNAME: "filecoin-mainnet-apn1-glif-dockerhub-glifio:username"
    DOCKERHUB_PASS: "filecoin-mainnet-apn1-glif-dockerhub-glifio:password"

phases:
  install:
    commands:
      - echo Environment Variables
      - printenv

  pre_build:
    commands:
      - echo Build STARTED
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASS
  build:
    commands:
      - echo Image built
      - cd ../../glifio/filecoin-docker/
      - docker build --network host --build-arg NETWORK=$IMAGE_NETWORK --build-arg BRANCH=$CUSTOM_WALLABY_TAG -t $IMAGE_NAME:latest . .

      - docker tag $IMAGE_NAME:latest $DOCKERUHUB_ORGANIZATION/lotus:wallaby_latest
      - docker push $DOCKERUHUB_ORGANIZATION/lotus:wallaby_latest
